DROP TABLE IF EXISTS times CASCADE;
CREATE TABLE times (
  id SERIAL PRIMARY KEY NOT NULL,
  event_id INT REFERENCES events(id) ON DELETE CASCADE,
  start_date VARCHAR(255) NOT NULL,
  end_date VARCHAR(255) NOT NULL
);
