DROP TABLE IF EXISTS votes CASCADE;
CREATE TABLE votes (
  id SERIAL PRIMARY KEY NOT NULL,
  voter_id SERIAL REFERENCES users(id) ON DELETE CASCADE,
  time_id SERIAL REFERENCES times(id) ON DELETE CASCADE,
  vote BOOLEAN
);
